# NixOS Integration Test for go-ffmpeg-hls-swarm
#
# This test spins up two VMs:
#   - origin: Nginx serving HLS content generated by FFmpeg
#   - client: Runs go-ffmpeg-hls-swarm against the origin
#
# Run with: nix build .#checks.x86_64-linux.integration-test
#
{ pkgs, self, ... }:

pkgs.testers.nixosTest {
  name = "go-ffmpeg-hls-swarm-integration";

  nodes = {
    # HLS Origin Server
    origin =
      { config, pkgs, ... }:
      {
        # Network configuration
        networking.firewall.allowedTCPPorts = [ 80 ];

        # Nginx serving HLS content
        services.nginx = {
          enable = true;
          virtualHosts."hls.test" = {
            root = "/var/www/hls";
            locations."/" = {
              extraConfig = ''
                # CORS headers for HLS
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods 'GET, OPTIONS';

                # Disable caching for live HLS
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires "0";

                # Proper MIME types
                types {
                  application/vnd.apple.mpegurl m3u8;
                  video/mp2t ts;
                }
              '';
            };
          };
        };

        # Create HLS directory
        systemd.tmpfiles.rules = [
          "d /var/www/hls 0755 nginx nginx -"
        ];

        # Generate test HLS stream using FFmpeg
        # This creates a 60-second test pattern video split into HLS segments
        systemd.services.generate-hls = {
          description = "Generate test HLS stream";
          after = [
            "network.target"
            "nginx.service"
          ];
          wantedBy = [ "multi-user.target" ];

          serviceConfig = {
            Type = "oneshot";
            User = "nginx";
            Group = "nginx";
            WorkingDirectory = "/var/www/hls";
            RemainAfterExit = true;
          };

          script = ''
            # Generate a 60-second test video as HLS
            # Using testsrc2 for a more interesting pattern
            ${pkgs.ffmpeg}/bin/ffmpeg -y \
              -f lavfi -i "testsrc2=duration=60:size=1280x720:rate=30" \
              -f lavfi -i "sine=frequency=1000:duration=60" \
              -c:v libx264 -preset ultrafast -tune zerolatency \
              -c:a aac -b:a 128k \
              -f hls \
              -hls_time 2 \
              -hls_list_size 0 \
              -hls_segment_filename "segment_%03d.ts" \
              stream.m3u8

            echo "HLS stream generated successfully"
            ls -la /var/www/hls/
          '';
        };
      };

    # go-ffmpeg-hls-swarm Client
    client =
      { config, pkgs, ... }:
      {
        environment.systemPackages = [
          self.packages.${pkgs.system}.default
          pkgs.ffmpeg
          pkgs.curl
        ];

        # Enable networking services for test
        networking.useDHCP = false;
        networking.interfaces.eth1.useDHCP = true;

        # Increase file descriptor limits for load testing
        security.pam.loginLimits = [
          {
            domain = "*";
            type = "soft";
            item = "nofile";
            value = "8192";
          }
          {
            domain = "*";
            type = "hard";
            item = "nofile";
            value = "16384";
          }
        ];
      };
  };

  testScript = ''
    start_all()

    # Wait for origin to be ready
    origin.wait_for_unit("nginx.service")
    origin.wait_for_unit("generate-hls.service")
    origin.wait_for_open_port(80)

    # Verify HLS content is accessible
    with subtest("HLS playlist is accessible"):
        origin.succeed("curl -sf http://localhost/stream.m3u8 | head -5")
        result = origin.succeed("curl -sf http://localhost/stream.m3u8")
        assert "#EXTM3U" in result, "Missing EXTM3U tag"
        assert "#EXTINF" in result, "Missing EXTINF tag"
        print(f"✓ HLS playlist valid:\n{result[:500]}")

    # Test from client VM
    with subtest("Client can reach origin"):
        client.wait_for_unit("multi-user.target")
        # Wait for network to be ready by polling
        client.wait_until_succeeds("ping -c 1 origin", timeout=30)
        client.succeed("curl -sf http://origin/stream.m3u8 | head -5")
        print("✓ Client can reach origin")

    # Verify FFmpeg can play the stream
    with subtest("FFmpeg can consume HLS stream"):
        # Run FFmpeg for a few seconds to verify it works
        # Using -t 3 to read only 3 seconds of content
        # The VOD stream has ~60 seconds of content
        result = client.succeed(
            "timeout 30 ffmpeg -hide_banner -loglevel warning "
            "-i http://origin/stream.m3u8 "
            "-t 3 -c copy -f null - 2>&1 || true"
        )
        # Verify we got some output (even errors are OK, we just want to confirm FFmpeg tried)
        client.succeed("echo 'FFmpeg attempted to read HLS stream'")
        print("✓ FFmpeg can consume HLS stream")

    # Test go-ffmpeg-hls-swarm
    with subtest("go-ffmpeg-hls-swarm shows version"):
        result = client.succeed("go-ffmpeg-hls-swarm --version")
        assert "go-ffmpeg-hls-swarm" in result
        print(f"✓ Version: {result.strip()}")

    # =================================================================
    # TODO: Enable these tests once implementation is complete
    # =================================================================
    #
    # with subtest("go-ffmpeg-hls-swarm runs with single client"):
    #     import time
    #     # Run with 1 client for 10 seconds (background)
    #     client.succeed(
    #         "timeout 15 go-ffmpeg-hls-swarm "
    #         "-clients 1 -duration 10s "
    #         "http://origin/stream.m3u8 &"
    #     )
    #     time.sleep(3)  # Give it time to start
    #
    #     # Check metrics endpoint
    #     result = client.succeed("curl -sf http://localhost:9090/metrics")
    #     assert "hlsswarm_clients_active" in result
    #     print("✓ Metrics endpoint responding")
    #
    # with subtest("go-ffmpeg-hls-swarm handles multiple clients"):
    #     client.succeed(
    #         "timeout 25 go-ffmpeg-hls-swarm "
    #         "-clients 5 -ramp-rate 2 -duration 20s "
    #         "http://origin/stream.m3u8"
    #     )
    #     print("✓ Multiple clients test passed")
    # =================================================================

    print("")
    print("=" * 60)
    print("  ✅ All integration tests passed!")
    print("=" * 60)
  '';
}
